rock_artists = [
    "The Beatles",
    "Led Zeppelin",
    "Pink Floyd",
    "The Rolling Stones",
    "Queen",
    "Nirvana",
    "Foo Fighters",
    "AC/DC",
    "Guns N' Roses",
    "Aerosmith",
    "Red Hot Chili Peppers",
    "Metallica",
    "Pearl Jam",
    "U2",
    "Linkin Park",
    "The Who",
    "The Doors",
    "Green Day",
    "Radiohead",
    "The Eagles",
    "R.E.M.",
    "Blink-182",
    "The Clash",
    "Oasis",
    "Bon Jovi",
    "Deep Purple",
    "The Kinks",
    "The White Stripes",
    "The Smashing Pumpkins",
    "Rage Against The Machine",
    "System of a Down",
    "Alice in Chains",
    "Soundgarden",
    "Muse",
    "The Black Keys",
    "Arctic Monkeys",
    "Paramore",
    "Kings of Leon",
    "Nine Inch Nails",
    "KISS",
    "Def Leppard",
    "Lynyrd Skynyrd",
    "Creedence Clearwater Revival",
    "Journey",
    "ZZ Top",
    "The Police",
    "Van Halen",
    "Santana",
    "The Strokes",
    "Mötley Crüe",
    "Rush",
    "Yes",
    "Fleetwood Mac",
    "Genesis",
    "Billy Idol",
    "The Cure",
    "Depeche Mode",
    "Stone Temple Pilots",
    "Bush",
    "Weezer",
    "Smash Mouth",
    "Evanescence",
    "Panic! At The Disco",
    "My Chemical Romance",
    "Fall Out Boy",
    "Nickelback",
    "3 Doors Down",
    "Seether",
    "Shinedown",
    "Breaking Benjamin",
    "Chevelle",
    "Disturbed",
    "Godsmack",
    "Five Finger Death Punch",
    "Avenged Sevenfold",
    "Slipknot"
]

pop_artists = [
    "Taylor Swift",
    "Ariana Grande",
    "Justin Bieber",
    "Beyoncé",
    "Ed Sheeran",
    "Lady Gaga",
    "Katy Perry",
    "Bruno Mars",
    "Rihanna",
    "Dua Lipa",
    "Billie Eilish",
    "Selena Gomez",
    "Shawn Mendes",
    "Harry Styles",
    "The Weeknd",
    "Sam Smith",
    "Adele",
    "Khalid",
    "Halsey",
    "Camila Cabello",
    "Lizzo",
    "Demi Lovato",
    "Charlie Puth",
    "Maroon 5",
    "Miley Cyrus",
    "Olivia Rodrigo",
    "Doja Cat",
    "Post Malone",
    "Sia",
    "Nick Jonas",
    "Jonas Brothers",
    "Britney Spears",
    "Christina Aguilera",
    "Ellie Goulding",
    "Kesha",
    "Shakira",
    "Jennifer Lopez",
    "Pink",
    "Alicia Keys",
    "Jason Derulo",
    "Cardi B",
    "Meghan Trainor",
    "Carly Rae Jepsen",
    "Tove Lo",
    "Zara Larsson",
    "Charli XCX",
    "Rita Ora",
    "Ellie Goulding",
    "Lana Del Rey",
    "Kacey Musgraves",
    "Niall Horan",
    "Liam Payne",
    "Louis Tomlinson",
    "Troye Sivan",
    "Bebe Rexha",
    "Alessia Cara",
    "Julia Michaels",
    "Ava Max",
    "Tinashe",
    "Jessie J",
    "Hailee Steinfeld",
    "Normani",
    "Madonna",
    "Whitney Houston",
    "Celine Dion",
    "Mariah Carey",
    "Kelly Clarkson",
    "Janet Jackson",
    "Alicia Keys",
    "Sia",
    "Michael Jackson",
    "Prince",
    "Elton John",
    "Cher",
    "Phil Collins",
    "John Legend",
    "Stevie Wonder",
    "Diana Ross",
    "Barbra Streisand",
    "Paul McCartney",
    "Rod Stewart",
    "Billy Joel",
    "George Michael",
    "Robbie Williams",
    "Annie Lennox",
    "Lionel Richie",
    "Bryan Adams",
    "Barry Manilow"
]

country_artists = [
    "Johnny Cash",
    "Dolly Parton",
    "Garth Brooks",
    "Willie Nelson",
    "Reba McEntire",
    "George Strait",
    "Shania Twain",
    "Kenny Rogers",
    "Carrie Underwood",
    "Luke Bryan",
    "Blake Shelton",
    "Tim McGraw",
    "Miranda Lambert",
    "Keith Urban",
    "Chris Stapleton",
    "Kacey Musgraves",
    "Brad Paisley",
    "Jason Aldean",
    "Eric Church",
    "Florida Georgia Line",
    "Thomas Rhett",
    "Sam Hunt",
    "Zac Brown Band",
    "Lady A",
    "Rascal Flatts",
    "Martina McBride",
    "Alan Jackson",
    "Loretta Lynn",
    "Hank Williams",
    "Patsy Cline",
    "Merle Haggard",
    "Waylon Jennings",
    "George Jones",
    "Vince Gill",
    "Alabama",
    "Brooks & Dunn",
    "Faith Hill",
    "Trisha Yearwood",
    "Dierks Bentley",
    "Scotty McCreery",
    "Maren Morris",
    "Brantley Gilbert",
    "Kip Moore",
    "Old Dominion",
    "Kane Brown",
    "Little Big Town",
    "Sugarland",
    "Josh Turner",
    "Lee Brice",
    "Jake Owen",
    "Brett Young",
    "Cole Swindell",
    "Randy Travis",
    "Jimmie Allen",
    "Gabby Barrett",
    "Carly Pearce",
    "Luke Combs",
    "Chris Young",
    "Maddie & Tae",
    "Dan + Shay",
    "Midland",
    "Jon Pardi",
    "Ashley McBryde",
    "Tanya Tucker",
    "Hunter Hayes",
    "Trace Adkins",
    "Kenny Chesney",
    "Clint Black",
    "Sara Evans",
    "Rodney Atkins",
    "Justin Moore",
    "Travis Tritt",
    "Easton Corbin",
    "Joe Nichols",
    "David Nail",
    "Tyler Childers",
    "Sturgill Simpson",
    "Parker McCollum",
    "Cody Johnson",
    "Cody Jinks",
    "Aaron Watson",
    "Lyle Lovett",
    "Jamey Johnson",
    "Dwight Yoakam",
    "Hank Williams Jr.",
    "Emmylou Harris",
    "Glen Campbell",
    "Tammy Wynette",
    "Conway Twitty",
    "Charley Pride",
    "Ronnie Milsap",
    "Jerry Reed",
    "Marty Robbins",
    "Crystal Gayle",
    "Anne Murray"
]